title: .me
description: Own your knowledge graph.
url: https://neurons-me.github.io
baseurl: "/.me"

remote_theme: neurons-me/neurons-me

plugins:
  - jekyll-remote-theme

exclude:
  - Python
  - Rust
  - node_modules
  - "*/node_modules"
  - vendor
  - Typescript/node_modules
  - Typescript/dist
  - Typescript/src
  - Typescript/x.test
  - Typescript/bench.ts
  - Typescript/reports

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

me_theme:
  brand: .me
  nav:
    - label: Home
      url: https://neurons-me.github.io/
    - label: Github
      url: https://github.com/neurons-me
    - label: All.This
      url: https://neurons-me.github.io/all.this/
