title: .me
description: Own your knowledge graph.
url: https://neurons-me.github.io
baseurl: "/.me"

remote_theme: neurons-me/neurons-me

plugins:
  - jekyll-remote-theme

exclude:
  - Python
  - Rust
  - node_modules
  - "*/node_modules"
  - vendor
  - Typescript/node_modules
  - Typescript/dist
  - Typescript/src
  - Typescript/x.test
  - Typescript/bench.ts
  - Typescript/reports

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

me_theme:
  brand: .me
  favicon: "https://res.cloudinary.com/dkwnxf6gm/image/upload/v1760915741/this.me-removebg-preview_1_nrj6pe.png"
  nav:
    - label: Home
      url: https://neurons-me.github.io/
    - label: Docs
      relative_url: /docs/
    - label: Github
      url: https://github.com/neurons-me/.me
    - label: All.This
      url: https://neurons-me.github.io/all.this/
